### ISSUE TITLE
CI: Do a format/clippy check as well

### ISSUE THREAD

**Issue by Hoverbear** [alyssais/memsocket#3]
I see you added CI! :+1: 

You may want to add a `cargo fmt` or `cargo clippy` run to your CI builds. 

Example of doing `fmt`:

https://github.com/pingcap/raft-rs/blob/01424b85980677fdbcd3fd82c736dab6918532f6/.travis.yml#L14-L19

Example of doing `clippy`

https://github.com/pingcap/raft-rs/blob/01424b85980677fdbcd3fd82c736dab6918532f6/.travis.yml#L21-L26

**Comment by alyssais** [comment]
Thanks for the examples! I notice the clippy version is pinned while the rustfmt version isn’t. What’s the reason for that?

**Comment by Hoverbear** [comment]
We use a particular nightly version for TiKV, so we pinned on the same clippy/nightly for it.

Partially this is because we don't want newly introduced lints or breakages in clippy/nightly blocking upcoming PRs. (Eg clippy adds a new lint and we need to change 100 lines unrelated to this PR.)

Partially this is because TiKV uses Raft and we want to ensure that the build works correctly on the build TiKV builds on. (build build build build)

**Comment by alyssais** [comment]
That makes sense. But rustfmt isn't 1.0, right? Couldn't it also introduce some change and force you to change 100 unrelated lines?

**Comment by Hoverbear** [comment]
It does yes. :( Generally it's pinned to a specific compiler version though.
